name: Build Multi-Architecture Docker Image

on:
  push:
    branches:
      - branchHTTPservMulti

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Встановлення QEMU для емуляції
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Крок 3: Налаштування Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Крок 4: Логін у Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Крок 5: Збірка та завантаження образу
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: Dasha05896/lab2:multiarch
